yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/yatube/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

handler404 = 'posts.views.page_not_found'  # noqa
handler500 = 'posts.views.server_error'  # noqa


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls')),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include(('about.urls', 'about'), namespace='about')),
]

if settings.DEBUG:
    urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)))
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

yatube/templates/base.html
<!doctype html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}The Last Social Media You'll Ever Need{% endblock %} | Yatube</title>
    <!-- Загрузка статики -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"
            integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
          integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js"
            integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns"
            crossorigin="anonymous"></script>
    <script src="https://use.fontawesome.com/f2751dab85.js"></script>
</head>

<body>

{% include 'header.html' %}

<main class="bg-body">
    <div class="container">
        <h1>{% block header %}The Last Social Media You'll Ever Need{% endblock %}</h1>

        {% block content %}
            <!-- Содержимое страницы -->
        {% endblock %}
    </div>
</main>

{% include 'footer.html' %}

</body>

</html>

yatube/templates/footer.html
<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <p class="m-0 text-dark text-center ">
        <a href="{% url 'about:author' %}">Об авторе</a>
        <a href="{% url 'about:tech' %}">Технологии</a>
    </p>
    <p class="m-0 text-dark text-center ">
        Социальная сеть <span style="color:red">Ya</span>tube © {% now 'Y' %}, все права защищены.
    </p>
</footer>

yatube/templates/header.html
<header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'index' %}"><span style="color:red">Ya</span>tube</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    {% if user.is_authenticated %}
                        <li class="nav-item ">
                            <a class="nav-link text-info" href="{% url 'profile' username=user.username %}">
                                Пользователь: {{ user.username }}
                            </a>
                        </li>
                        <li class="nav-item ">
                            <a class="nav-link text-info" href="{% url 'password_change' %}">Изменить пароль</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-info" href="{% url 'logout' %}">Выйти</a>
                        </li>
                        <li class="nav-item{% if nav_bar == 'new_post' %} active{% endif %}">
                            <a class="nav-link" href="{% url 'new_post' %} ">Новая запись</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link text-info" href="{% url 'login' %}">Войти</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-info" href="{% url 'signup' %}">Регистрация</a>
                        </li>
                    {% endif %}
                    <li class="nav-item{% if nav_bar == 'groups' %} active{% endif %}">
                        <a class="nav-link" href="{% url 'groups' %} ">Сообщества</a>
                    </li>
                </ul>
            </div>
        </nav>
</header>

yatube/templates/index.html
{% extends "base.html" %}
{% block title %}Последние обновления на сайте{% endblock %}
{% block header %}Последние обновления на сайте{% endblock %}
{% block content %}

    {% include 'menu.html'  with index=True %}
    {% include 'paginator.html' %}

    {% for post in page %}

        <div class="col-md-15">
            {% include 'post_item.html' with post=post %}
        </div>

    {% endfor %}

    {% include 'paginator.html' %}

{% endblock %} 

yatube/templates/paginator.html
{% if page.has_other_pages %}
  <nav>
    <ul class="pagination">
      {% if page.has_previous %}
        <li class="page-item">
          <a
            class="page-link"
            href="?page={{ page.previous_page_number }}">&laquo;</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <span class="page-link">&laquo;</span>
        </li>
      {% endif %}
      {% for i in page.paginator.page_range %}
        {% if page.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}
              <span class="sr-only">(текущая)</span>
            </span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
      {% endfor %}
      {% if page.has_next %}
        <li class="page-item">
          <a
            class="page-link"
            href="?page={{ page.next_page_number }}">&raquo;</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <span class="page-link">&raquo;</span>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}